### ISSUE TITLE
*Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.*

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/gdal#1]
```
$ pip-review --auto --local
...
Requirement already satisfied: GDAL in /usr/lib/python3/dist-packages (3.4.1)
Collecting GDAL
  Using cached GDAL-3.8.0.tar.gz (802 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info
      writing /tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-45go5dv3/GDAL.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 89, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 190, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 92, in fetch_config
          raise gdal_config_error(e)
      __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 360, in <module>
          setup(
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/home/mint/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 266, in finalize_options
          gdaldir = self.get_gdal_config('prefix')
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 196, in get_gdal_config
          raise gdal_config_error(traceback_string + '\n' + msg)
      __main__.gdal_config_error: Traceback (most recent call last):
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 89, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 190, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-p0b2c7wp/gdal_40cef01bb8b54a6691acbfc24d038123/setup.py", line 92, in fetch_config
          raise gdal_config_error(e)
      gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
      
      Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I have not achieved to solve the issue by just installing the appropriate package with `apt` (note that I found such a package).

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by Benjamin-Loison** [comment]
```
Requirement already satisfied: GDAL in /usr/lib/python3/dist-packages (3.4.1)
Collecting GDAL
  Downloading GDAL-3.8.2.tar.gz (802 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.5/802.5 kB 6.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info
      writing /tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-93h862qu/GDAL.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 89, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 190, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 92, in fetch_config
          raise gdal_config_error(e)
      __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 360, in <module>
          setup(
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 266, in finalize_options
          gdaldir = self.get_gdal_config('prefix')
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 196, in get_gdal_config
          raise gdal_config_error(traceback_string + '\n' + msg)
      __main__.gdal_config_error: Traceback (most recent call last):
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 89, in fetch_config
          p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 190, in get_gdal_config
          return fetch_config(option, gdal_config=self.gdal_config)
        File "/tmp/pip-install-5km7jttr/gdal_c30b0eb6312b46af82f388ac40312ec0/setup.py", line 92, in fetch_config
          raise gdal_config_error(e)
      gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
      
      Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Defaulting to user installation because normal site-packages is not writeable
```

**Comment by Benjamin-Loison** [comment]
If I:

```bash
sudo apt install -y libgdal-dev
```

Then I get:

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: GDAL in /usr/lib/python3/dist-packages (3.4.1)
Collecting GDAL
  Using cached GDAL-3.8.2.tar.gz (802 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info
      writing /tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-pm66fe_m/GDAL.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ma1s89j9/gdal_ce367f2fb740404b81edcd4f0781ba1c/setup.py", line 360, in <module>
          setup(
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/home/benjamin/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-ma1s89j9/gdal_ce367f2fb740404b81edcd4f0781ba1c/setup.py", line 235, in finalize_options
          raise Exception(f"Python bindings of GDAL {version} require at least libgdal {version}, but {library_version} was found")
      Exception: Python bindings of GDAL 3.8.2 require at least libgdal 3.8.2, but 3.4.1 was found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```

With:

```bash
apt show libgdal-dev
```

```
Package: libgdal-dev
Version: 3.4.1+dfsg-1build4
Priority: extra
Section: universe/libdevel
Source: gdal
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 59.2 MB
Depends: libgdal30 (= 3.4.1+dfsg-1build4), libc6-dev, libarmadillo-dev, libblosc-dev, libcfitsio-dev, libcharls-dev, libcurl4-gnutls-dev | libcurl-ssl-dev, libdeflate-dev, libexpat1-dev, libfreexl-dev, libfyba-dev, libgeos-dev, libgeotiff-dev (>= 1.5.0), libgif-dev, libhdf4-alt-dev, libhdf5-dev, libheif-dev, libjpeg-dev, libjson-c-dev, libkml-dev, libltdl-dev, liblz4-dev, liblzma-dev, default-libmysqlclient-dev, libnetcdf-dev, libogdi-dev, libopenjp2-7-dev, libpcre2-dev, libpng-dev, libpoppler-private-dev, libpq-dev, libproj-dev (>= 6.0.0), libqhull-dev, libspatialite-dev, libsqlite3-dev, libtiff-dev, liburiparser-dev, libwebp-dev, libxerces-c-dev, libxml2-dev, libzstd-dev, unixodbc-dev
Homepage: http://www.gdal.org/
Download-Size: 10.6 MB
APT-Manual-Installed: yes
APT-Sources: http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
Description: Geospatial Data Abstraction Library - Development files
 GDAL is a translator library for raster geospatial data formats.
 As a library, it presents a single abstract data model to the
 calling application for all supported formats. The related OGR
 library (which lives within the GDAL source tree) provides
 a similar capability for simple features vector data.
 .
 GDAL supports many popular data formats, including commonly used
 ones (GeoTIFF, JPEG, PNG and more) as well as the ones used in
 GIS and remote sensing software packages (ERDAS Imagine,
 ESRI Arc/Info, ENVI, PCI Geomatics). Also supported many remote
 sensing and scientific data distribution formats such as HDF,
 EOS FAST, NOAA L1B, NetCDF, FITS.
 .
 OGR library supports popular vector formats like ESRI Shapefile,
 TIGER data, S57, MapInfo File, DGN, GML and more.
 .
 This package contains the files needed to develop a software that
 will use the GDAL/OGR (headers, static objects, configuration script).
```

**Comment by Benjamin-Loison** [comment]
`"Python bindings of GDAL" "require at least libgdal" "but" "was found"` does not lead to any result with DuckDuckGo but not Google.

**Comment by Benjamin-Loison** [comment]
```bash
pip uninstall gdal
```
```
Found existing installation: GDAL 3.4.1
Uninstalling GDAL-3.4.1:
  Would remove:
    /usr/lib/python3/dist-packages/GDAL-3.4.1.egg-info
    /usr/lib/python3/dist-packages/osgeo
    /usr/lib/python3/dist-packages/osgeo_utils
Proceed (Y/n)? Y
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/GDAL-3.4.1.egg-info' -> '/tmp/pip-uninstall-ykedpicy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 725, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 381, in remove
    moved.stash(path)
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 272, in stash
    renames(path, new_path)
  File "/home/benjamin/.local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 362, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.10/shutil.py", line 834, in move
    rmtree(src)
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'PKG-INFO'
```

```bash
sudo pip uninstall gdal
```
```
Found existing installation: GDAL 3.4.1
Not uninstalling gdal at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'GDAL'. No files were found to uninstall.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

```bash
sudo rm -R /usr/lib/python3/dist-packages/GDAL-3.4.1.egg-info/
```
```
pip uninstall gdal
```
```
WARNING: Skipping gdal as it is not installed.
```

**Comment by Benjamin-Loison** [comment]
It seems I solved the issue by removing GDAL pip package, I hope I have not broken anything.
